-- ════════════════════════════════════════════════════════════════════
-- Ruta 38 Repuestos — esquema de Supabase
-- Recrea desde cero las tablas que index.html espera. Los nombres de
-- columna están tal cual los usa el código (algunos en camelCase entre
-- comillas), así que no hace falta tocar el JS para que funcione.
--
-- Cómo usarlo:
--   1. Crear un proyecto nuevo en supabase.com
--   2. Project Settings → API → copiar "Project URL" y la "anon public" key
--   3. Pegar esos dos valores en index.html, líneas ~3095-3096
--      (SUPABASE_URL y SUPABASE_KEY)
--   4. Correr este archivo completo en el SQL Editor del proyecto
--   5. Abrir index.html, entrar con el PIN, y en la consola (F12) pegar
--      el contenido de cargar_datos.js para precargar categorías y marcas
-- ════════════════════════════════════════════════════════════════════

-- ── PRODUCTOS ──
create table public.productos (
  id             bigint generated by default as identity primary key,
  codigo         text,
  nombre         text not null,
  categoria      text,
  marca          text,
  precio         numeric(12,2) not null default 0,
  costo          numeric(12,2) not null default 0,
  stock          integer not null default 0,
  "stockDeposito" integer not null default 0,
  "minStock"     integer not null default 0,
  activos        boolean not null default true,
  created_at     timestamptz not null default now()
);
create index productos_codigo_idx on public.productos (codigo);
create index productos_nombre_idx on public.productos (nombre);
create index productos_activos_idx on public.productos (activos);

-- ── VENTAS ──
create table public.ventas (
  id         bigint generated by default as identity primary key,
  fecha      timestamptz not null default now(),
  total      numeric(12,2) not null default 0,
  pago       numeric(12,2) not null default 0,
  vuelto     numeric(12,2) not null default 0,
  anulada    boolean not null default false
);
create index ventas_fecha_idx on public.ventas (fecha desc);

-- ── ITEMS (detalle de cada venta) ──
create table public.items (
  id           bigint generated by default as identity primary key,
  venta_id     bigint not null references public.ventas (id) on delete cascade,
  producto_id  bigint references public.productos (id) on delete set null,
  cantidad     integer not null,
  precio       numeric(12,2) not null,
  subtotal     numeric(12,2) not null
);
create index items_venta_id_idx on public.items (venta_id);

-- ── CATEGORÍAS ──
create table public.categorias (
  id      bigint generated by default as identity primary key,
  nombre  text not null unique,
  activa  boolean not null default true
);

-- ── MARCAS ──
-- OJO: "nombre" acá no es solo el nombre de la marca — cargar_datos.js
-- guarda "Toyota|Corolla,Camry,Hilux,..." (marca + modelos separados por
-- coma) en el mismo campo. No se puede poner UNIQUE porque el código
-- también permite crear marcas sueltas sin modelos desde el tab Admin
-- (agregarMarca solo manda el nombre). Es una mezcla rara pero es la que
-- espera el front-end tal cual está hoy.
create table public.marcas (
  id      bigint generated by default as identity primary key,
  nombre  text not null,
  activa  boolean not null default true
);

-- ════════════════════════════════════════════════════════════════════
-- RLS — Row Level Security
-- ════════════════════════════════════════════════════════════════════
-- La app NO tiene login contra Supabase (usa siempre la misma "anon key",
-- visible en el código fuente del navegador). Habilitar RLS acá y darle
-- permiso total al rol "anon" deja el comportamiento IGUAL al de hoy
-- (cualquiera con la key puede leer/escribir todo) — no es una capa de
-- seguridad real todavía. Lo que sí gana: RLS queda prendido por defecto
-- (postura correcta), así que el día que agreguen login de verdad
-- (Supabase Auth), alcanza con cambiar estas policies por unas que
-- exijan auth.uid(), sin tener que activar RLS por primera vez a mitad
-- de una migración con datos reales adentro.
alter table public.productos  enable row level security;
alter table public.ventas     enable row level security;
alter table public.items      enable row level security;
alter table public.categorias enable row level security;
alter table public.marcas     enable row level security;

create policy "anon acceso total productos"  on public.productos  for all to anon using (true) with check (true);
create policy "anon acceso total ventas"     on public.ventas     for all to anon using (true) with check (true);
create policy "anon acceso total items"      on public.items      for all to anon using (true) with check (true);
create policy "anon acceso total categorias" on public.categorias for all to anon using (true) with check (true);
create policy "anon acceso total marcas"     on public.marcas     for all to anon using (true) with check (true);
