-- ════════════════════════════════════════════════════════════════════
-- Ruta 38 Repuestos — esquema de Supabase
-- Recrea desde cero las tablas que index.html espera. Los nombres de
-- columna están tal cual los usa el código (algunos en camelCase entre
-- comillas), así que no hace falta tocar el JS para que funcione.
--
-- Cómo usarlo:
--   1. Crear un proyecto nuevo en supabase.com
--   2. Project Settings → API → copiar "Project URL" y la "anon public" key
--   3. Pegar esos dos valores en index.html, en las variables
--      SUPABASE_URL y SUPABASE_KEY (buscarlas con Ctrl+F)
--   4. Correr este archivo completo en el SQL Editor del proyecto
--   5. Authentication → Users → "Add user": crear el email y la contraseña
--      del local (marcar "Auto Confirm User")
--   6. Authentication → Sign In / Providers → DESACTIVAR
--      "Allow new users to sign up" (ver nota en la sección RLS)
--   7. Abrir index.html, entrar con ese email/contraseña y el PIN, y en la
--      consola (F12) pegar cargar_datos.js para precargar categorías y marcas
--
-- ¿La base ya existía con una versión anterior? No corras este archivo:
-- corré supabase_migracion.sql (agrega lo nuevo sin borrar datos).
-- ════════════════════════════════════════════════════════════════════

-- ── PRODUCTOS ──
create table public.productos (
  id             bigint generated by default as identity primary key,
  codigo         text,
  nombre         text not null,
  categoria      text,
  marca          text,
  precio         numeric(12,2) not null default 0,
  costo          numeric(12,2) not null default 0,
  stock          integer not null default 0,
  "stockDeposito" integer not null default 0,
  "minStock"     integer not null default 0,
  activos        boolean not null default true,
  created_at     timestamptz not null default now()
);
create index productos_codigo_idx on public.productos (codigo);
create index productos_nombre_idx on public.productos (nombre);
create index productos_activos_idx on public.productos (activos);

-- ── VENTAS ──
create table public.ventas (
  id         bigint generated by default as identity primary key,
  fecha      timestamptz not null default now(),
  total      numeric(12,2) not null default 0,
  pago       numeric(12,2) not null default 0,
  vuelto     numeric(12,2) not null default 0,
  metodo     text not null default 'efectivo',  -- efectivo | transferencia | debito | credito
  anulada    boolean not null default false,
  uid        text  -- id generado en la caja; evita duplicar ventas al reintentar
);
create index ventas_fecha_idx on public.ventas (fecha desc);
create unique index ventas_uid_key on public.ventas (uid);

-- ── ITEMS (detalle de cada venta) ──
create table public.items (
  id           bigint generated by default as identity primary key,
  venta_id     bigint not null references public.ventas (id) on delete cascade,
  producto_id  bigint references public.productos (id) on delete set null,
  cantidad     integer not null,
  precio       numeric(12,2) not null,
  subtotal     numeric(12,2) not null
);
create index items_venta_id_idx on public.items (venta_id);

-- ── CATEGORÍAS ──
create table public.categorias (
  id      bigint generated by default as identity primary key,
  nombre  text not null unique,
  activa  boolean not null default true
);

-- ── MARCAS ──
-- OJO: "nombre" acá no es solo el nombre de la marca — cargar_datos.js
-- guarda "Toyota|Corolla,Camry,Hilux,..." (marca + modelos separados por
-- coma) en el mismo campo. No se puede poner UNIQUE porque el código
-- también permite crear marcas sueltas sin modelos desde el tab Admin
-- (agregarMarca solo manda el nombre). Es una mezcla rara pero es la que
-- espera el front-end tal cual está hoy.
create table public.marcas (
  id      bigint generated by default as identity primary key,
  nombre  text not null,
  activa  boolean not null default true
);

-- ════════════════════════════════════════════════════════════════════
-- RLS — Row Level Security
-- ════════════════════════════════════════════════════════════════════
-- La "anon key" está a la vista en el código fuente del navegador, así que
-- por sí sola NO da acceso a nada: solo el rol "authenticated" (alguien que
-- entró con el email y la contraseña del local) puede leer y escribir.
--
-- IMPORTANTE: en Supabase → Authentication → Sign In / Providers hay que
-- DESACTIVAR "Allow new users to sign up". Si queda activado, cualquiera con
-- la anon key podría crearse su propia cuenta y pasar a ser "authenticated".
alter table public.productos  enable row level security;
alter table public.ventas     enable row level security;
alter table public.items      enable row level security;
alter table public.categorias enable row level security;
alter table public.marcas     enable row level security;

drop policy if exists "anon acceso total productos"  on public.productos;
drop policy if exists "anon acceso total ventas"     on public.ventas;
drop policy if exists "anon acceso total items"      on public.items;
drop policy if exists "anon acceso total categorias" on public.categorias;
drop policy if exists "anon acceso total marcas"     on public.marcas;

drop policy if exists "local acceso total productos"  on public.productos;
drop policy if exists "local acceso total ventas"     on public.ventas;
drop policy if exists "local acceso total items"      on public.items;
drop policy if exists "local acceso total categorias" on public.categorias;
drop policy if exists "local acceso total marcas"     on public.marcas;

create policy "local acceso total productos"  on public.productos  for all to authenticated using (true) with check (true);
create policy "local acceso total ventas"     on public.ventas     for all to authenticated using (true) with check (true);
create policy "local acceso total items"      on public.items      for all to authenticated using (true) with check (true);
create policy "local acceso total categorias" on public.categorias for all to authenticated using (true) with check (true);
create policy "local acceso total marcas"     on public.marcas     for all to authenticated using (true) with check (true);

-- ════════════════════════════════════════════════════════════════════
-- FUNCIONES DE STOCK
-- ════════════════════════════════════════════════════════════════════
-- El stock se suma/resta EN LA BASE (stock = stock - cantidad), nunca se
-- escribe un número calculado en el navegador. Así dos cajas que venden el
-- mismo producto al mismo tiempo no se pisan: Postgres las pone en fila.
-- Son "security invoker": corren con los permisos (y RLS) de quien las llama.

-- Stock actual de los productos de una venta — lo usa la app para refrescar su caché.
create or replace function public.stocks_de_venta(p_venta_id bigint)
returns jsonb language sql stable security invoker set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', p.id, 'stock', p.stock)), '[]'::jsonb)
  from public.productos p
  where p.id in (select producto_id from public.items where venta_id = p_venta_id);
$$;

-- Anula una venta y devuelve su stock. Si ya estaba anulada no hace nada
-- (se puede llamar dos veces sin devolver el stock dos veces).
create or replace function public.anular_venta(p_venta_id bigint)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  v_anulada boolean;
begin
  select anulada into v_anulada from public.ventas where id = p_venta_id for update;
  if not found then
    raise exception 'La venta % no existe', p_venta_id;
  end if;
  if not v_anulada then
    update public.ventas set anulada = true where id = p_venta_id;
    update public.productos p set stock = p.stock + x.cant
    from (select producto_id, sum(cantidad) as cant from public.items
          where venta_id = p_venta_id and producto_id is not null group by producto_id) x
    where p.id = x.producto_id;
  end if;
  return jsonb_build_object('venta_id', p_venta_id, 'stocks', public.stocks_de_venta(p_venta_id));
end;
$$;

-- Registra venta + items + descuento de stock en una sola transacción.
-- p_venta: {uid, fecha, total, pago, vuelto, metodo, anulada}
-- p_items: [{producto_id, cantidad, precio}, ...]
-- "uid" lo genera la caja: si la misma venta llega dos veces (reintento de la
-- cola offline, respuesta perdida) se devuelve la ya guardada, sin duplicar.
-- Si llega con anulada=true (se anuló mientras esperaba en la cola) no descuenta stock.
create or replace function public.registrar_venta(p_venta jsonb, p_items jsonb)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  v_uid     text    := nullif(p_venta->>'uid', '');
  v_anulada boolean := coalesce((p_venta->>'anulada')::boolean, false);
  v_id      bigint;
begin
  insert into public.ventas (uid, fecha, total, pago, vuelto, metodo, anulada)
  values (
    v_uid,
    coalesce((p_venta->>'fecha')::timestamptz, now()),
    coalesce((p_venta->>'total')::numeric, 0),
    coalesce((p_venta->>'pago')::numeric, 0),
    coalesce((p_venta->>'vuelto')::numeric, 0),
    coalesce(nullif(p_venta->>'metodo', ''), 'efectivo'),
    v_anulada
  )
  on conflict (uid) do nothing
  returning id into v_id;

  if v_id is null then
    -- Ya estaba registrada: no se vuelve a insertar ni a descontar.
    select id into v_id from public.ventas where uid = v_uid;
    if v_anulada then
      return public.anular_venta(v_id);
    end if;
    return jsonb_build_object('venta_id', v_id, 'stocks', public.stocks_de_venta(v_id));
  end if;

  insert into public.items (venta_id, producto_id, cantidad, precio, subtotal)
  select v_id,
         (select p.id from public.productos p where p.id = nullif(i->>'producto_id', '')::bigint),
         (i->>'cantidad')::integer,
         (i->>'precio')::numeric,
         (i->>'cantidad')::integer * (i->>'precio')::numeric
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as i;

  if not v_anulada then
    update public.productos p set stock = p.stock - x.cant
    from (select producto_id, sum(cantidad) as cant from public.items
          where venta_id = v_id and producto_id is not null group by producto_id) x
    where p.id = x.producto_id;
  end if;

  return jsonb_build_object('venta_id', v_id, 'stocks', public.stocks_de_venta(v_id));
end;
$$;

-- Pasa unidades del depósito al negocio. Falla si en el depósito no alcanza.
create or replace function public.mover_stock(p_id bigint, p_cant integer)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  r jsonb;
begin
  update public.productos
     set stock = stock + p_cant, "stockDeposito" = "stockDeposito" - p_cant
   where id = p_id and p_cant > 0 and "stockDeposito" >= p_cant
  returning jsonb_build_object('id', id, 'stock', stock, 'stockDeposito', "stockDeposito") into r;
  if r is null then
    raise exception 'No hay suficiente stock en depósito';
  end if;
  return r;
end;
$$;

-- Suma (o resta, con números negativos) stock en lote: carga rápida con escáner,
-- importación de mercadería y "deshacer". Suma sobre el valor de la base, así no
-- pisa ventas hechas mientras tanto. p_items: [{id, negocio, deposito}, ...]
create or replace function public.ajustar_stock(p_items jsonb)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  r jsonb;
begin
  with x as (
    select (e->>'id')::bigint as id,
           sum(coalesce((e->>'negocio')::integer, 0))  as neg,
           sum(coalesce((e->>'deposito')::integer, 0)) as dep
    from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as e
    group by 1
  ), u as (
    update public.productos p
       set stock = p.stock + x.neg, "stockDeposito" = p."stockDeposito" + x.dep
      from x
     where p.id = x.id
    returning p.id, p.stock, p."stockDeposito"
  )
  select coalesce(jsonb_agg(jsonb_build_object('id', id, 'stock', stock, 'stockDeposito', "stockDeposito")), '[]'::jsonb)
    into r from u;
  return r;
end;
$$;

revoke all on function public.stocks_de_venta(bigint)       from public, anon;
revoke all on function public.anular_venta(bigint)          from public, anon;
revoke all on function public.registrar_venta(jsonb, jsonb) from public, anon;
revoke all on function public.mover_stock(bigint, integer)  from public, anon;
revoke all on function public.ajustar_stock(jsonb)           from public, anon;
grant execute on function public.stocks_de_venta(bigint)       to authenticated;
grant execute on function public.anular_venta(bigint)          to authenticated;
grant execute on function public.registrar_venta(jsonb, jsonb) to authenticated;
grant execute on function public.mover_stock(bigint, integer)  to authenticated;
grant execute on function public.ajustar_stock(jsonb)           to authenticated;
