-- ════════════════════════════════════════════════════════════════════
-- Migración 001 — ADITIVA (paso 1 del plan de endurecimiento)
--
-- Solo AGREGA columnas, tablas e índices. No borra ni cambia nada de lo
-- que usa index.html hoy, así que la app actual sigue funcionando igual.
-- Es idempotente: se puede correr más de una vez.
--
-- Antes de correrla: hacer el backup del paso 0 (ver supabase/README.md)
-- y probarla primero en el proyecto de STAGING.
-- ════════════════════════════════════════════════════════════════════

begin;

-- ── VENTAS: método de pago + clave de idempotencia ──
-- metodo_pago: hoy el front lo calcula pero no lo guarda (ver cobrar() en
-- index.html). Las ventas históricas quedan como 'efectivo' porque ese dato
-- nunca se persistió: es una suposición, no un dato real.
alter table public.ventas
  add column if not exists metodo_pago text not null default 'efectivo';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ventas_metodo_pago_check'
  ) then
    alter table public.ventas
      add constraint ventas_metodo_pago_check
      check (metodo_pago in ('efectivo', 'transferencia', 'debito', 'credito'));
  end if;
end $$;

-- client_uuid: lo genera el navegador al armar la venta. Con UNIQUE, un
-- reintento offline de la misma venta no puede duplicarla (lo usará la RPC
-- registrar_venta del paso 2). NULL para las ventas anteriores.
alter table public.ventas
  add column if not exists client_uuid uuid;

create unique index if not exists ventas_client_uuid_uidx
  on public.ventas (client_uuid)
  where client_uuid is not null;

-- ── ITEMS: snapshot de lo vendido ──
-- Hoy el historial reconstruye el nombre desde el catálogo ACTUAL; si el
-- producto se renombra o se da de baja, la venta vieja queda distorsionada.
alter table public.items
  add column if not exists nombre       text,
  add column if not exists costo        numeric(12,2),
  add column if not exists precio_lista numeric(12,2);

-- Backfill best-effort con los valores actuales del producto. El costo y el
-- nombre pueden no coincidir con los de la fecha de la venta: es lo mejor
-- disponible. Solo toca filas que todavía no tienen snapshot.
update public.items i
   set nombre = p.nombre,
       costo  = p.costo
  from public.productos p
 where i.producto_id = p.id
   and i.nombre is null;

-- ── ÍNDICES ──
create index if not exists items_producto_id_idx
  on public.items (producto_id);

-- ── MOVIMIENTOS DE STOCK (ledger) ──
-- Cada cambio de stock queda registrado (venta, anulación, traspaso, ajuste).
-- cantidad es con signo respecto a la ubicación indicada.
-- Todavía nada escribe acá: lo usarán las RPC del paso 2.
create table if not exists public.movimientos_stock (
  id           bigint generated by default as identity primary key,
  producto_id  bigint not null references public.productos (id),
  ubicacion    text   not null check (ubicacion in ('negocio', 'deposito')),
  tipo         text   not null check (tipo in ('venta', 'anulacion', 'traspaso', 'ajuste', 'alta')),
  cantidad     integer not null check (cantidad <> 0),
  venta_id     bigint references public.ventas (id) on delete set null,
  nota         text,
  created_by   uuid default auth.uid(),
  created_at   timestamptz not null default now()
);

create index if not exists movimientos_stock_producto_idx
  on public.movimientos_stock (producto_id, created_at desc);
create index if not exists movimientos_stock_venta_idx
  on public.movimientos_stock (venta_id);

-- RLS activado y SIN policies: nadie (anon ni authenticated) puede leerla o
-- escribirla directamente. Solo las funciones security definer del paso 2
-- van a operar sobre ella. La app actual no la toca.
alter table public.movimientos_stock enable row level security;

commit;

-- ── ROLLBACK manual (si hiciera falta) ──
-- drop table if exists public.movimientos_stock;
-- drop index if exists public.items_producto_id_idx;
-- alter table public.items  drop column if exists nombre, drop column if exists costo, drop column if exists precio_lista;
-- drop index if exists public.ventas_client_uuid_uidx;
-- alter table public.ventas drop column if exists client_uuid;
-- alter table public.ventas drop constraint if exists ventas_metodo_pago_check;
-- alter table public.ventas drop column if exists metodo_pago;
